export const FETCH_TRACK_DATA = "FETCH_TRACK_DATA";
export const FETCH_TRACK_DATA_SUCCEEDEED = "FETCH_TRACK_DATA_SUCCEEDEED";

export const FETCH_LYRIC_DATA = "FETCH_LYRIC_DATA";
export const FETCH_LYRIC_DATA_SUCCEEDEED = "FETCH_LYRIC_DATA_SUCCEEDEED";

export const FETCH_TRACK_LYRIC_DATA = "FETCH_TRACK_LYRIC_DATA";
export const FETCH_TRACK_LYRIC_DATA_SUCCEEDEED = "FETCH_TRACK_LYRIC_DATA_SUCCEEDEED";

export const FETCH_TRACK_DATA_BY_SEARCH = "FETCH_TRACK_DATA_BY_SEARCH";
export const FETCH_TRACK_DATA_BY_SEARCH_SUCCEEDEED = "FETCH_TRACK_DATA_BY_SEARCH_SUCCEEDEED";

export const CLEAR_TRACK_TRACK_LYRIC_DATA = "CLEAR_TRACK_TRACK_LYRIC_DATA";
export const CLEAR_LYRIC_TRACK_DATA_SUCCEEDEED = "CLEAR_LYRIC_TRACK_DATA_SUCCEEDEED";
